var deck = [
	{"rankNum": 1,	"rankSpell": "red joker",	"suitValue": 0,	"suitName": "jokers"	},
	{"rankNum": 2,	"rankSpell": "black joker",	"suitValue": 0,	"suitName": "jokers"	},
	
	{"rankNum": 1,	"rankSH": "A",	"rankSpell": "ace",		"rankPlural": "aces",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 2,	"rankSH": "2",	"rankSpell": "two",		"rankPlural": "twos",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 3,	"rankSH": "3",	"rankSpell": "three",	"rankPlural": "threes",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 4,	"rankSH": "4",	"rankSpell": "four",	"rankPlural": "fours",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 5,	"rankSH": "5",	"rankSpell": "five",	"rankPlural": "fives",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 6,	"rankSH": "6",	"rankSpell": "six",		"rankPlural": "sixes",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 7,	"rankSH": "7",	"rankSpell": "seven",	"rankPlural": "sevens",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 8,	"rankSH": "8",	"rankSpell": "eight",	"rankPlural": "eights",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 9,	"rankSH": "9",	"rankSpell": "nine",	"rankPlural": "nines",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 10,	"rankSH": "10",	"rankSpell": "ten",		"rankPlural": "tens",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 11,	"rankSH": "J",	"rankSpell": "jack",	"rankPlural": "jacks",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 13,	"rankSH": "Q",	"rankSpell": "queen",	"rankPlural": "queens",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 14,	"rankSH": "K",	"rankSpell": "king",	"rankPlural": "kings",		"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	
	{"rankNum": 1,	"rankSH": "A",	"rankSpell": "ace",		"rankPlural": "aces",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 2,	"rankSH": "2",	"rankSpell": "two",		"rankPlural": "twos",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 3,	"rankSH": "3",	"rankSpell": "three",	"rankPlural": "threes",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 4,	"rankSH": "4",	"rankSpell": "four",	"rankPlural": "fours",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 5,	"rankSH": "5",	"rankSpell": "five",	"rankPlural": "fives",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 6,	"rankSH": "6",	"rankSpell": "six",		"rankPlural": "sixes",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 7,	"rankSH": "7",	"rankSpell": "seven",	"rankPlural": "sevens",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 8,	"rankSH": "8",	"rankSpell": "eight",	"rankPlural": "eights",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 9,	"rankSH": "9",	"rankSpell": "nine",	"rankPlural": "nines",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 10,	"rankSH": "10",	"rankSpell": "ten",		"rankPlural": "tens",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 11,	"rankSH": "J",	"rankSpell": "jack",	"rankPlural": "jacks",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 13,	"rankSH": "Q",	"rankSpell": "queen",	"rankPlural": "queens",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 14,	"rankSH": "K",	"rankSpell": "king",	"rankPlural": "kings",		"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	
	{"rankNum": 1,	"rankSH": "A",	"rankSpell": "ace",		"rankPlural": "aces",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 2,	"rankSH": "2",	"rankSpell": "two",		"rankPlural": "twos",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 3,	"rankSH": "3",	"rankSpell": "three",	"rankPlural": "threes",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 4,	"rankSH": "4",	"rankSpell": "four",	"rankPlural": "fours",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 5,	"rankSH": "5",	"rankSpell": "five",	"rankPlural": "fives",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 6,	"rankSH": "6",	"rankSpell": "six",		"rankPlural": "sixes",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 7,	"rankSH": "7",	"rankSpell": "seven",	"rankPlural": "sevens",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 8,	"rankSH": "8",	"rankSpell": "eight",	"rankPlural": "eights",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 9,	"rankSH": "9",	"rankSpell": "nine",	"rankPlural": "nines",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 10,	"rankSH": "10",	"rankSpell": "ten",		"rankPlural": "tens",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 11,	"rankSH": "J",	"rankSpell": "jack",	"rankPlural": "jacks",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 13,	"rankSH": "Q",	"rankSpell": "queen",	"rankPlural": "queens",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 14,	"rankSH": "K",	"rankSpell": "king",	"rankPlural": "kings",		"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	
	{"rankNum": 1,	"rankSH": "A",	"rankSpell": "ace",		"rankPlural": "aces",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 2,	"rankSH": "2",	"rankSpell": "two",		"rankPlural": "twos",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 3,	"rankSH": "3",	"rankSpell": "three",	"rankPlural": "threes",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 4,	"rankSH": "4",	"rankSpell": "four",	"rankPlural": "fours",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 5,	"rankSH": "5",	"rankSpell": "five",	"rankPlural": "fives",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 6,	"rankSH": "6",	"rankSpell": "six",		"rankPlural": "sixes",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 7,	"rankSH": "7",	"rankSpell": "seven",	"rankPlural": "sevens",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 8,	"rankSH": "8",	"rankSpell": "eight",	"rankPlural": "eights",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 9,	"rankSH": "9",	"rankSpell": "nine",	"rankPlural": "nines",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 10,	"rankSH": "10",	"rankSpell": "ten",		"rankPlural": "tens",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 11,	"rankSH": "J",	"rankSpell": "jack",	"rankPlural": "jacks",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 13,	"rankSH": "Q",	"rankSpell": "queen",	"rankPlural": "queens",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	{"rankNum": 14,	"rankSH": "K",	"rankSpell": "king",	"rankPlural": "kings",		"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},

	{"rankNum": 12,	"rankSH": "C",	"rankSpell": "cavalier",	"rankPlural": "cavaliers",	"suitValue": 1,	"suitSymbol": "♥",	"suitName": "hearts"	},
	{"rankNum": 12,	"rankSH": "C",	"rankSpell": "cavalier",	"rankPlural": "cavaliers",	"suitValue": 1,	"suitSymbol": "♣",	"suitName": "clubs"		},
	{"rankNum": 12,	"rankSH": "C",	"rankSpell": "cavalier",	"rankPlural": "cavaliers",	"suitValue": 1,	"suitSymbol": "♦",	"suitName": "diamonds"	},
	{"rankNum": 12,	"rankSH": "C",	"rankSpell": "cavalier",	"rankPlural": "cavaliers",	"suitValue": 1,	"suitSymbol": "♠",	"suitName": "spades"	},
	
	{"rankNum": 0,	"rankSpell": "the fool",			"rankRom": "0",		"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 1,	"rankSpell": "the magician",		"rankRom": "I",		"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 2,	"rankSpell": "the high priestess",	"rankRom": "II",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 3,	"rankSpell": "the empress",			"rankRom": "III",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 4,	"rankSpell": "the emperor",			"rankRom": "IV",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 5,	"rankSpell": "the hierophant",		"rankRom": "V",		"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 6,	"rankSpell": "the lovers",			"rankRom": "VI",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 7,	"rankSpell": "the chariot",			"rankRom": "VII",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 8,	"rankSpell": "strength",			"rankRom": "VIII",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 9,	"rankSpell": "the hermit",			"rankRom": "IX",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 10,	"rankSpell": "wheel of fortune",	"rankRom": "X",		"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 11,	"rankSpell": "justice",				"rankRom": "XI",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 12,	"rankSpell": "the hanged man",		"rankRom": "XII",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 13,	"rankSpell": "death",				"rankRom": "XIII",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 14,	"rankSpell": "temperance",			"rankRom": "XIV",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 15,	"rankSpell": "the devil",			"rankRom": "XV",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 16,	"rankSpell": "the tower",			"rankRom": "XVI",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 17,	"rankSpell": "the star",			"rankRom": "XVII",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 18,	"rankSpell": "the moon",			"rankRom": "XVIII",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 19,	"rankSpell": "the sun",				"rankRom": "XIX",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 20,	"rankSpell": "judgement",			"rankRom": "XX",	"suitValue": 5,	"suitName": "trumps"	},
	{"rankNum": 21,	"rankSpell": "the world",			"rankRom": "XXI",	"suitValue": 5,	"suitName": "trumps"	}
];
